When(/^I add a new expense by clicking New Expense button$/) do
  @purchases_page = @tallie_page
  @purchases_page.add_via_popup('merchant' => 'Cucumber Auto', 'reason' => 'Generated by Cucumber-auto', 'amount' => '100.00')

end