require_relative '../../../../Tallie/Login/features/step_definitions/login_steps'
require_relative '../../../../Tallie/Login/features/LoginPage'

Given /^I (am on|go to) Purchases page$/ do |temp|
  step %{I am logged in to Tallie}  #TODO need to bypass login and go to purchases page
  @tallie_page = PurchasesPage.new(@driver)
  @purchases_page = @tallie_page
end


When(/^I add a new expense by clicking New Expense button$/) do
  @purchases_page.add_via_popup('merchant' => 'Cucumber Auto', 'reason' => 'Generated by Cucumber-auto', 'amount' => '100.00')

end